apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: energy
    user: postgres
    secureJsonData:
      password: postgres
    isDefault: true
    jsonData:
      database: energy
      sslmode: disable
      pgVersion: 1400
